apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: private-quarkus-devfile-sample-tynn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: private-quarkus-devfile-sample-tynn
    app.kubernetes.io/part-of: private-devfile
  name: private-quarkus-devfile-sample-tynn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: private-quarkus-devfile-sample-tynn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: private-quarkus-devfile-sample-tynn
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-zlgx-tenant/private-devfile/private-quarkus-devfile-sample-tynn@sha256:ca67cfaba589d74cff8d42a8ebd6e12f10a427eac26d3137c6187e5f96a463c5
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
