apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: private-quarkus-devfile-sample-tynn
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-zlgx-tenant/private-devfile/private-quarkus-devfile-sample-tynn@sha256:ca67cfaba589d74cff8d42a8ebd6e12f10a427eac26d3137c6187e5f96a463c5
        name: my-java-quarkus
        resources: {}
status: {}
